#ifndef _PHONE_TASK_H
#define _PHONE_TASK_H

#include <stdint.h>
#include <generated/phoneGen.h>
#include <libTime.h>

#define SMS_PRINTF_LENGTH_FOR_DEBUG 20

#define BAND_NA 0x00
#define BAND_850 0x01
#define BAND_900 0x02
#define BAND_1800 0x04
#define BAND_1900 0x08


bool getSim2PresenceStatus(void);
uint8_t modemIsReady(void);
void phoneTask(void const *argument);
void phoneNetworkStats(void);
int phoneTaskBackgroud(void);
int sendToModemWithTimeout(void);
void receiveModemData(char data);
void handleDataTransmissionError(void);
void errorCommandCallbackHandler(char *command);
void successCommandCallbackHandler(char *command);
void errorCommandCallbackHandler(char *command);
simNumber_t getMainSIM(void);
void errorCommandCallbackHandler(char *command);
void setPhoneTaskTimeout(uint32_t timeout);

char *getLastVoiceCallError(void);
void setMainSIM(simNumber_t *simNumber);

#define SIM_PIN_PUK_MAXLENGTH 12
#define PIN_MIN_LENGTH 4
#define PUK_MIN_LENGTH 8

#define SMS_RECIPIENT_NUMBER_MIN_LENGTH 3
#define SIM_CARD_NUMBERS 2
#define STORED_COMMAND_MAX_SIZE 256

#define ONE_SECOND 1000
typedef enum timeoutValue_e
{
  SECONDS_2 = 2 * ONE_SECOND,
  SECONDS_5 = 5 * ONE_SECOND,
  SECONDS_30 = 30 * ONE_SECOND,
  SECONDS_60 = 60 * ONE_SECOND,
  SECONDS_120 = 120 * ONE_SECOND,
  timeoutValue_num,
} timeoutValue_t;

enum
{
  FIRST_INT_IN_STRING = 0,
  SECOND_INT_IN_STRING,
  THIRD_INT_IN_STRING,
  FOURTH_INT_IN_STRING,
  FIFTH_INT_IN_STRING,
  SIXTH_INT_IN_STRING,
};

enum
{
  USSD_NO_FURTHER_USER_ACTION_REQ = 0,
  USSD_FURTHER_USER_ACTION_REQUIRED,
  USSD_TERMINATED_BY_NETWORK,
  USSD_OTHER_LOCAL_CLIENT_HAS_RESPONDED,
  USSD_OPERATION_NOT_SUPPORTER,
  USSD_NETWORK_TIME_OUT
};

typedef struct
{
  int messageId;
  simNumber_t simNumber; // informacje ktory sim odebral sms
  char senderNumber[20]; // numer nadawcy
  char senderName[20];
  sysTime_t smsTime; // czas nadejscia wiadomosci
  sysDate_t smsDate;  // data nadejscia wiadomosci
  int receivedMessageLength; // calkowita dlugosc wiadomosci
  int smsAlphabet; // tryb kodowania
  uint8_t wholeMessageReceivedFlag; // flaga informujaca ze odebrano cala wiadomosc
  char smsMessage[]; // calkowita wiadomosc
} received_sms_t;

typedef struct
{
  int messageId;
  simNumber_t simNumber;
  char recipientNumber[20];
  int alphabet;
  uint16_t textLength;
  char messageToSend[];
} send_sms_t;

typedef struct
{
  int messageId;
  simNumber_t simNumber;
  char *errorMessage;
} sms_send_error_t;


#define SMSC_MAX_NUMBER_LENGTH 20
typedef struct smsCenter_Number_s
{
  char smsCenterNumberSim1[SMSC_MAX_NUMBER_LENGTH]; //SMSC number SIM1
  char smsCenterNumberSim2[SMSC_MAX_NUMBER_LENGTH]; //SMSC number SIM2
} smsCenter_Number_t;

enum
{
  MODEM_OK,
  MODEM_ERROR,
  MODEM_INCOMING_CALL_CALLER_NUMBER_SIM1,
  MODEM_INCOMING_CALL_CALLER_NUMBER_SIM2,
  MODEM_CALL_STARTED_SIM1,
  MODEM_CALL_STARTED_SIM2,
  MODEM_CALL_STARTED_FROM_CALLER_SIDE_SIM2,
  MODEM_CALL_ENDED_SIM1,
  MODEM_CALL_ENDED_SIM2,
  MODEM_CALL_ENDED_FROM_CALLER_SIDE_SIM1,
  MODEM_CALL_ENDED_FROM_CALLER_SIDE_SIM2,
  MODEM_NETWORK_REGISTATION_OK_SIM1,
  MODEM_NETWORK_REGISTATION_OK_SIM2,
  MODEM_SIGNAL_QUALITY_SIM1,
  MODEM_SIGNAL_QUALITY_SIM2,
  MOBILE_START_UP_REPORTING_SIM1,
  MOBILE_START_UP_REPORTING_SIM2,
  MODEM_NETWORK_REGISTRATION_INFO_SIM1,
  MODEM_NETWORK_REGISTRATION_INFO_SIM2,
  MODEM_SET_SPEAKER_VOLUME,
  MODEM_NEW_SMS_SIM1,
  MODEM_NEW_SMS_SIM2,
  MODEM_SMS_SEND_OK_SIM1,
  MODEM_SMS_SEND_OK_SIM2,
  MODEM_READ_PHONEBOOK_FIND_SIM1,
  MODEM_READ_PHONEBOOK_FIND_SIM2,
  MODEM_CMD_SMS_READ_SIM1,
  MODEM_CMD_SMS_READ_SIM2,
  MODEM_CMD_SMS_SMSC_SIM1,
  MODEM_CMD_SMS_SMSC_SIM2,
  MODEM_NETWORK_GET_NETWORK_TIME,
  MODEM_NETWORK_TIME_ZONE_CHANGE,
  MODEM_USSD_RESP_SIM1,
  MODEM_USSD_RESP_SIM2,
  MODEM_FIELD_STRENGTH,
  MODEM_ACTUAL_BAND_SIM1,
  MODEM_ACTUAL_BAND_SIM2,
  MODEM_POWER_CLASS,
  CMS_ERROR,
  CME_ERROR,
  CME_IMEI_SIM1,
  CME_IMEI_SIM2,
  CME_BAND_CLASS,
  MODEM_SERVICE_READY_SIM1,
  MODEM_SERVICE_READY_SIM2,
  CME_PHONE_BOOK_IS_READY_SIM1,
  CME_PHONE_BOOK_IS_READY_SIM2,
  MODEM_READ_PHONEBOOK_CONFIG_SIM1,
  MODEM_READ_PHONEBOOK_CONFIG_SIM2,
  MODEM_READ_PHONEBOOK_ENTRY_SIM1,
  MODEM_READ_PHONEBOOK_ENTRY_SIM2,
  MODEM_ECHO,
  MODEM_RING_SIM1,
  MODEM_RING_SIM2,
  MODEM_CRING_SIM1,
  MODEM_CRING_SIM2,
  MODEM_NO_CARRIER,
  MODEM_BUSY,
  MODEM_REPORTING_STATUS_SIM1,
  MODEM_REPORTING_STATUS_SIM2,
  MODEM_SMS_MEMORY,
  MODEM_ZONE_INDICATION_SIM1,
  MODEM_ZONE_INDICATION_SIM2,
  MODEM_SERVICE_READY_GENERIC_SIM1,
  MODEM_SERVICE_READY_GENERIC_SIM2,
  MODEM_CALLS_IN_PROGRESS_SIM1,
  MODEM_CALLS_IN_PROGRESS_SIM2,
  MODEM_PROMPT,
  MODEM_PIN_REQUIRED_SIM1,
  MODEM_PIN_REQUIRED_SIM2,
  MODEM_PIN_NOT_REQUIRED_SIM1,
  MODEM_PIN_NOT_REQUIRED_SIM2,
  MODEM_PUK_REQUIRED_SIM1,
  MODEM_PUK_REQUIRED_SIM2,
  MODEM_PASSWORD_ATTEMPTS_LEFT_SIM1,
  MODEM_PASSWORD_ATTEMPTS_LEFT_SIM2,
  MODEM_PHONEBOOK_MEMORY_USAGE_SIM1,
  MODEM_PHONEBOOK_MEMORY_USAGE_SIM2,
  MODEM_FW_VERSION,
  MODEM_EXTENDED_CALL_ERROR_REPORT,
  MODEM_NO_DIALTONE,
  MODEM_DIAL_BUSY,
  MODEM_NO_ANSWER,

  modem_cmd_num,
};

enum
{
  CME_PHONE_FAILURE,
  CME_NO_CONNECTION_TO_PHONE,
  CME_PHONE_ADAPTER_LINK_RESERVED,
  CME_OPERATION_NOT_ALLOWED,
  CME_OPERATION_NOT_SUPPORTED,
  CME_PH_SIM_PIN_REQUIRED,
  CME_PH_FSIM_PIN_REQUIRED,
  CME_PH_FSIM_PUK_REQUIRED,
  CME_SIM_NOT_INSERTED,
  CME_SIM_PIN_REQUIRED,
  CME_SIM_PUK_REQUIRED,
  CME_SIM_FAILURE,
  CME_SIM_BUSY,
  CME_SIM_WRONG,
  CME_INCORRECT_PASSWORD,
  CME_SIM_PIN2_REQUIRED,
  CME_SIM_PUK2_REQUIRED,
  CME_MEMORY_FULL,
  CME_INVALID_INDEX,
  CME_NOT_FOUND,
  CME_MEMORY_FAILURE,
  CME_TEXT_STRING_TOO_LONG,
  CME_INVALID_CHARACTERS_IN_TEXT_STRING,
  CME_DIAL_STRING_TOO_LONG,
  CME_INVALID_CHARACTERS_IN_DIAL_STRING,
  CME_NOT_NETWORK_SERVICE,
  CME_NETWORK_TIMEOUT,
  CME_EMERGENCY_CALL_ONLY,
  CME_NETWORK_PERSONALIZATION_PIN_REQUIRED,
  CME_NETWORK_PERSONALIZATION_PUK_REQUIRED,
  CME_NETWORK_SUBSET_PERSONALIZATION_PIN_REQUIRED,
  CME_NETWORK_SUBSET_PERSONALIZATION_PUK_REQUIRED,
  CME_SERVICE_PROVIDER_PERSONALIZATION_PIN_REQUIRED,
  CME_SERVICE_PROVIDER_PERSONALIZATION_PUK_REQUIRED,
  CME_CORPORATE_PERSONALIZATION_PIN_REQUIRED,
  CME_CORPORATE_PERSONALIZATION_PUK_REQUIRED,
  CME_RESOURCE_LIMITATION,
  CME_SYNCHRONIZATIN_ERROR,
  CME_GPRS_SERVICES_NOT_ALLOWED,
  CME_PLMN_NOT_ALLOWED,
  CME_LOCATION_AREA_NOT_ALLOWED,
  CME_ROAMING_NOT_ALLOWERD,
  CME_SERVICE_OPTION_NOT_SUPPORTED,
  CME_REQUEST_SERVICE_OPTION_NOT_SUBSCRIBED,
  CME_SERVICE_OPTION_TEMP_OUT_OF_ORDER,
  CME_UNSPECIFIED_GPRS_ERROR,
  CME_PDP_AUTHENTICATION_FAILURE,
  CME_INVALID_MOBILE_CLASS,
  CME_NO_MORE_SOCETS_AVAILABLE,
  CME_MEMORY_PROBLEM,
  CME_DNS_ERROR,
  CME_TCP_DISCONNECTION_BY_SERVER,
  CME_TCP_UDP_CONNECTION_ERROR,
  CME_GENERIC_ERROR,
  CME_FAIL_TO_ACCEPT_CLIENT_REQUEST,
  CME_INCOHERENT_DATA,
  CME_BAD_SESSION_ID,
  CME_SESSION_ALREADY_RUNNING,
  CME_NO_MORE_SESSIONS_AVAILABLE,
  CME_SOCKET_CONNECTION_TIMEOUT,
  CME_CONTROL_SOCKET_CONNECTION_TIMEOUT,
  CME_PARAMETER_NOT_EXPECTED,
  CME_PARAMETER_INVALID_VALUE_RANGE,
  CME_PARAMETER_MISSING,
  CME_FEATURE_NOT_SUPPORTED,
  CME_FEATURE_NOT_AVAILABLE,
  CME_PROTOCOL_NOT_SUPPORTED,
  CME_INVALID_BEARER_CONNECTION_STATE,
  CME_INVALID_SESSION_STATE,
  CME_INVALID_TERMINAL_PORT_STATE,
  CME_SESSION_BUSY,
  CME_HTTP_HEADER_NAME_MISSING,
  CME_HTTP_HEADER_VALUE_MISSING,
  CME_HTTP_HEADER_NAME_EMPTY_STRING,
  CME_HTTP_HEADER_VALUE_EMPTY_STRING,
  CME_INPUT_DATA_INVALID_FORMAT,
  CME_INPUT_DATA_INVALID_CONTENT,
  CME_INVALID_PARAMETER_LENGTH,
  CME_INVALID_PARAMETER_FORMAT,
  modem_cme_err_num,
};

enum
{
  CMS_UNASSIGNED_NUMBER,
  CMS_OPERATOR_DETERMINED_BARRING,
  CMS_CALL_BARRED,
  CMS_SHORT_MESSAGE_TRANSFER_REJECTED,
  CMS_DESTINATION_OUT_OF_SERVICE,
  CMS_UNIDENTYFIED_SUBSCRIBER,
  CMS_FACILITY_REJECTED,
  CMS_UNKNOWN_SUBSCRIBER,
  CMS_NETWORK_OUT_OF_ORDER,
  CMS_TEMPORARY_FAILURE,
  CMS_CONGESTION,
  CMS_RESOURCES_UNAVAILABLE,
  CMS_FACILITY_BOT_SUBSCRIBED,
  CMS_FACILITY_NOT_IMPLEMENTED,
  CMS_INVALID_SHORT_MESSAGE_REFERENCE_VALUE,
  CMS_INVALID_MESSAGE,
  CMS_INVALID_MANDATORY_INFORMATION,
  CMS_MESSAGE_TYPE_NON_EXISTENT,
  CMS_MESSAGE_NOT_COMPATIBILE_WITH_PROTOCOL,
  CMS_INFORMATION_ELEMENT_NON_EXISTENT,
  CMS_PROTOCOL_ERROR,
  CMS_INTERWORKING,
  CMS_TELEMATIC_INTERWORKING,
  CMS_SHORT_MESSAGE_TYPE0_NOT_SUPPORTED,
  CMS_CANNOT_REPLACE_SHORT_MESSAGE,
  CMS_UNSPECIFIED_TP_PID_ERROR,
  CMS_ALPHABET_NOT_SUPPORTED,
  CMS_MESSAGE_CLASS_NOT_SUPPORTED,
  CMS_UNSPECIFIED_TP_DCS_ERROR,
  CMS_COMMAND_CANNOT_BE_EXECUTED,
  CMS_COMMAND_UNSUPPORTED,
  CMS_UNSPECIFIED_TP_COMMAND_ERROR,
  CMS_TPDU_NOT_SUPPORTED,
  CMS_SC_BUSY,
  CMS_NO_SC_SUBSCRIPTION,
  CMS_SC_SYSTEM_FAILUER,
  CMS_INVALID_SME_ADDRESS,
  CMS_DESTINATION_SME_BARRED,
  CMS_SM_REJECTED,
  CMS_VPF_NOT_SUPPORTED,
  CMS_TP_BP_NOT_SUPPORTED,
  CMS_D0_SIM_STORAGE_FULL,
  CMS_NO_SMS_STORAGE_CAPABILITY,
  CMS_ERROR_IN_MS,
  CMS_MEMORY_CAPACITY_EXCEEDED,
  CMS_SIM_APPLICATION_TOOLKIT_BUSY,
  CMS_SIM_DATA_DOWNLOAD_ERROR,
  CMS_UNSPECIFIED_ERROR_CAUSE,
  CMS_ME_FAILUER,
  CMS_SMS_SERVICE_OF_ME_RESERVED,
  CMS_OPERATION_NOT_ALLOWED,
  CMS_OPERATION_NOT_SUPPORTED,
  CMS_INVALID_PDU_MODE_PARAMETER,
  CMS_INVALID_TEXT_MODE_PARAMETER,
  CMS_SIM_NOT_INSERTED,
  CMS_SIM_PIN_REQUIRED,
  CMS_PH_SIM_PIN_REQUIRED,
  CMS_SIM_FAILURE,
  CMS_SIM_BUSY,
  CMS_SIM_WRONG,
  CMS_SIM_PUK_REQUIRED,
  CMS_SIM_PIN2_REQUIRED,
  CMS_SIM_PUK2_REQUIRED,
  CMS_MEMORY_FAILURE,
  CMS_INVALID_MEMORY_INDEX,
  CMS_MEMORY_FULL,
  CMS_SMSC_ADDRESS_UNKNOWN,
  CMS_NO_NETWORK_SERVICE,
  CMS_NETWORK_TIMEOUT,
  CMS_NO_CNMA_ACK_EXPECTED,
  CMS_UNKNOWN_ERROR,
  modem_cms_err_num,
};

enum
{
  CEER_CAUSE_SELECT_0 = 0,
  CEER_CAUSE_SELECT_16 = 16,
  CEER_CAUSE_SELECT_65 = 65,
  CEER_CAUSE_SELECT_66 = 66,
  CEER_CAUSE_SELECT_67 = 67,
  CEER_CAUSE_SELECT_69 = 69,
  CEER_CAUSE_SELECT_71 = 71,
  CEER_CAUSE_SELECT_73 = 73,
};

enum
{
  CEER_0_NO_CAUSE = 0,
};

enum
{
  CEER_16_UNKNOWN = 0,
  CEER_16_NOT_ALLOWED = 1,
  CEER_16_NO_CAUSE = 2,
  CEER_16_WRONG_PARAMETER = 6,
  CEER_16_NETWORK_ACCESS_NOT_ALLOWED = 9,
  CEER_16_ALL_CALL_INSTANCES_ARE_USED = 20,
  CEER_16_ACM_OVER_ACM_MAX = 21,
  CEER_16_INVALID_AOC_ELEMENT = 22,
  CEER_16_SIM_INCREASE_NOT_ALLOWED = 23,
  CEER_16_SWITCH_OFF = 24,
  CEER_16_UNKNOWN_CALL_ID = 25,
  CEER_16_BARRED = 28,
};

enum
{
  CEER_65_STATE_ERROR = 1,
  CEER_65_NO_CALL_ENTITY = 2,
  CEER_65_WRONG_TI = 3,
  CEER_65_DTMF_BUFFER_OVERFLOW = 6,
  CEER_65_CALL_DISCONNECTED = 7,
  CEER_65_NO_CELL_AVAILABLE = 17,
  CEER_65_LOCAL_REJECTION = 32,
  CEER_65_PLMN_NOT_ALLOWED = 33,
  CEER_65_EMERGENCY_CALL_NOT_POSSIBLE = 34,
  CEER_65_AUTHENTICATION_REJECTED = 35,
  CEER_65_NETWORK_REJECTION = 36,
  CEER_65_LA_NOT_ALLOWED = 37,
  CEER_65_LOCAL_TIMEOUT = 38,
  CEER_65_SERVER_CONGESTION = 39,
  CEER_65_LOCAL_DATA_REJECTION = 40,
  CEER_65_FAILED_REPLACE_PDP_CONTEXT = 48,
};

enum
{
  CEER_66_NO_CAUSE_INFORMATION_AVAILABLE = 0,
  CEER_66_UNASSIGNED_UNALLOCATED_NUMBER = 1,
  CEER_66_NO_ROUTE_DESTINATION = 3,
  CEER_66_CHANNEL_UNACCEPTABLE = 6,
  CEER_66_OPERATOR_DETERMINED_BARRING = 8,
  CEER_66_NORMAL_CALL_CLEARING = 16,
  CEER_66_USER_BUSY = 17,
  CEER_66_NO_USER_RESPONDING = 18,
  CEER_66_USER_ALERTING_NO_ANSWER = 19,
  CEER_66_CALL_REJECTED = 21,
  CEER_66_NUMBER_CHANGED = 22,
  CEER_66_NON_SELECTED_USER_CLEARING = 26,
  CEER_66_DESTINATION_OUT_OF_ORDER = 27,
  CEER_66_INVALID_NUMBER_FORMAT_INCOMPLETE_NUMBER = 28,
  CEER_66_FACILITY_REJECTED = 29,
  CEER_66_RESPONSE_TO_STATUS_ENQUIIRY = 30,
  CEER_66_NORMAL_UNSPECIFIED = 31,
  CEER_66_NO_CIRCUIT_CHANNEL_AVAILABLE = 34,
  CEER_66_NETWORK_OUT_OF_ORDER = 38,
  CEER_66_TEMPORARY_FAILURE = 41,
  CEER_66_SWITCHING_EQUIPMENT_CONGESTION = 42,
  CEER_66_ACCESS_INFORMATION_DISCARDED = 43,
  CEER_66_REQUESTED_CIRCUIT_CHANNEL_NOT_AVAILABLE = 44,
  CEER_66_RESOURCES_UNAVAILABLE_UNSPECIFIED = 47,
  CEER_66_QUALITY_OF_SERVICE_UNAVAILABLE = 49,
  CEER_66_REQUESTED_FACILITY_NOT_SUBSCRIBED = 50,
  CEER_66_INCOMING_CALLS_BARRED_WITH_IN_THE_CUG = 55,
  CEER_66_BEARER_CAPABILITY_NOT_AUTHORIZED = 57,
  CEER_66_BEARER_CAPABILITY_NOT_PRESENTLY_AVAILABLE = 58,
  CEER_66_SERVICE_OR_OPTION_NOT_AVAILABLE_UNSPECIFIED = 63,
  CEER_66_BEARER_SERVICE_NOT_IMPLEMENTED = 65,
  CEER_66_ACM_EQUAL_TO_OR_GREATER_THAN_AC_MMAX = 68,
  CEER_66_REQUESTED_FACILITY_NOT_IMPLEMENTED = 69,
  CEER_66_ONLY_RESTRICTED_DIGITAL_INFORMATION_BEARER_CAPABILITY_IS_AVAILABLE = 70,
  CEER_66_SERVICE_OR_OPTION_NOT_IMPLEMENTED_UNSPECIFIED = 79,
  CEER_66_INVALID_TRANSACTION_IDENTIFIER_VALUE = 81,
  CEER_66_USER_NOT_MEMBER_OF_CUG = 87,
  CEER_66_INCOMPATIBLE_DESTINATION = 88,
  CEER_66_INVALID_TRANSIT_NETWORK_SELECTION = 91,
  CEER_66_SEMANTICALLY_INCORRECT_MESSAGE1 = 95,
  CEER_66_INVALID_MANDATORY_INFORMATION = 96,
  CEER_66_MESSAGE_TYPE_NON_EXISTENT_OR_NOT_IMPLEMENTED = 97,
  CEER_66_MESSAGE_TYPE_NOT_COMPATIBLE_WITH_PROTOCOL_STATE = 98,
  CEER_66_INFORMATION_ELEMENT_NON_EXISTENT_OR_NOT_IMPLEMENTED = 99,
  CEER_66_CONDITIONAL_IE_ERROR = 100,
  CEER_66_MESSAGE_NOT_COMPATIBLE_WITH_PROTOCOL_STATE = 101,
  CEER_66_RECOVERY_ON_TIMER_EXPIRY = 102,
  CEER_66_ILLEGAL_MS = 103,
  CEER_66_ILLEGAL_ME = 106,
  CEER_66_GPRS_SERVICE_NOT_ALLOWED = 107,
  CEER_66_PROTOCOL_ERROR_UNSPECIFIED1 = 111,
  CEER_66_LOCATION_AREA_NOT_ALLOWED = 112,
  CEER_66_ROAMING_NOT_ALLOWED_IN_THIS_LOCATION_AREA = 113,
  CEER_66_MBMS_BEARER_CAPABILITIES_INSUFFICIENT_FOR_THE_SERVICE = 124,
  CEER_66_LLC_OR_SNDCP_FAILURE = 125,
  CEER_66_INSUFFICIENT_RESOURCES = 126,
  CEER_66_MISSING_OR_UNKNOWN_APN = 127,
  CEER_66_UNKNOWN_PDP_ADDRESS_OR_PDP_TYPE = 128,
  CEER_66_USER_AUTHENTICATION_FAILED = 129,
  CEER_66_ACTIVATION_REJECTED_BY_GGSN = 130,
  CEER_66_ACTIVATION_REJECTUNSPECIFIED = 131,
  CEER_66_SERVICE_NOT_SUPPORTED = 132,
  CEER_66_REQUESTED_SERVICE_OPTION_NOT_SUBSCRIBED = 133,
  CEER_66_SERVICE_OPTION_TEMPORARILY_OUT_OF_ORDER = 134,
  CEER_66_NSAPI_ALREADY_USED = 135,
  CEER_66_REGULAR_PDP_CONTEXT_DEACTIVATION = 136,
  CEER_66_QOS_NOT_ACCEPTED = 137,
  CEER_66_NETWORK_FAILURE = 138,
  CEER_66_REACTIVATION_REQUESTED = 139,
  CEER_66_FEATURE_NOT_SUPPORTED = 140,
  CEER_66_SEMANTIC_ERROR_IN_THE_TFT_OPERATION = 141,
  CEER_66_SYNTACTICAL_ERROR_IN_THE_TFT_OPERATION = 142,
  CEER_66_UNKNOWN_PDP_CONTEXT = 143,
  CEER_66_SEMANTIC_ERRORS_IN_PACKET_FILTERS = 144,
  CEER_66_SYNTACTICAL_ERRORS_IN_PACKET_FILTERS = 145,
  CEER_66_PDP_CONTEXT_WITHOUT_TFT_ALREADY_ACTIVATED = 146,
  CEER_66_UNSPECIFIED_GPRS_ERROR = 148,
  CEER_66_PDP_AUTHENTIFICATION_ERROR = 149,
  CEER_66_APN_RESTRICTION = 212,
  CEER_66_INTERNAL_UNSPECIFIED = 256,
  CEER_66_OUT_OF_MEMORY = 257,
  CEER_66_INVALID_PARAMETERS = 258,
  CEER_66_DATA_CALL_ACTIVE = 259,
  CEER_66_SPEECH_CALL_ACTIVE = 260,
  CEER_66_MISSING_ACM_INFORMATION = 262,
  CEER_66_TEMPORARY_FORBIDDEN = 263,
  CEER_66_CALLED_PARTY_IS_BLACKLISTED = 264,
  CEER_66_BLACKLIST_IS_FULL = 265,
  CEER_66_NO_SERVICE = 266,
  CEER_66_LIMITED_SERVICE = 267,
  CEER_66_CLIENT_CONFLICT = 268,
  CEER_66_DUAL_SERVICE_CALL_ACTIVE = 269,
  CEER_66_UNKNOWN_SIM_ERROR = 271,
  CEER_66_ACTIVE_CLIENT_IS_GONE = 274,
  CEER_66_SIM_STATUS_FAILURE = 277,
  CEER_66_REJECTED_BY_CALL_CONTROL = 278,
  CEER_66_FDN_FAILED = 279,
  CEER_66_BDN_FAILED = 280,
  CEER_66_CCBS_POSSIBLE = 283,
  CEER_66_INVALID_ALTERNATE_SERVICE_LINE = 284,
  CEER_66_LND_OVERVIEW = 285,
  CEER_66_MM_NETWORK_FAILURE_UNSPECIFIED = 287,
  CEER_66_MM_NO_SERVICE = 288,
  CEER_66_MM_ACCESS_CLASS_BARRED = 289,
  CEER_66_MM_RR_NO_RESOURCE = 290,
  CEER_66_MM_ME_BUSY = 291,
  CEER_66_MM_UNSPECIFIED = 292,
  CEER_66_MMI_NOT_REGISTERED = 301,
  CEER_66_REJECTED_BY_USER = 303,
  CEER_66_REJECTED_DUE_TO_TIME_OUT = 304,
  CEER_66_DISCONNECTED_DUE_TO_SIM_TK_CALL_SETUP = 306,
  CEER_66_PENDING_SIM_TK_CALL_SETUP = 307,
  CEER_66_SIM_RESET = 310,
  CEER_66_MM_SAPI3_RELEASE = 340,
  CEER_66_MM_LOWER_LAYER_FAILURE = 341,
  CEER_66_MM_AUTHENTIFICATION_FAILURE = 342,
  CEER_66_MM_PS_REJECT = 343,
  CEER_66_MM_SERVICE_REJECTED = 344,
  CEER_66_MM_ABORT_BY_NETWORK = 345,
  CEER_66_MM_TIMEOUT = 346,
  CEER_66_MM_DETACH = 347,
  CEER_66_MM_RR_CONNECTION_RELEASE = 348,
  CEER_66_MM_NOT_REGISTERED = 349,
  CEER_66_MM_REESTABLISHMENT_FAILURE = 350,
  CEER_66_FAILURE_DUE_TO_HANDOVER = 351,
  CEER_66_LINK_ESTABLISHMENT_FAILURE = 352,
  CEER_66_RANDOM_ACCESS_FAILURE = 353,
  CEER_66_RADIO_LINK_ABORTED = 354,
  CEER_66_LOWER_LAYER_FAILURE_IN_LAYER_1 = 355,
  CEER_66_IMMEDIATE_ASSIGNMENT_REJECT = 356,
  CEER_66_FAILURE_DUE_TO_PAGING = 357,
  CEER_66_ABNORMAL_RELEASE_UNSPECIFIED = 358,
  CEER_66_ABNORMAL_RELEASE_CHANNEL_UNACCEPTABLE = 359,
  CEER_66_ABNORMAL_RELEASE_TIMER_EXPIRED = 360,
  CEER_66_ABNORMAL_RELEASE_NO_ACT_ON_RADIO_PATH = 361,
  CEER_66_PREEMPTIVE_RELEASE1 = 362,
  CEER_66_UTRAN_CONFIGURATION_UNKNOWN = 363,
  CEER_66_HANDOVER_IMPOSSIBLE = 364,
  CEER_66_CHANNEL_MODE_UNACCEPTABLE = 365,
  CEER_66_FREQUENCY_NOT_IMPLEMENTED = 366,
  CEER_66_ORIGINATOR_LEAVING_CALL_GROUP_AREA = 367,
  CEER_66_LOWER_LAYER_FAILURE_FROM_NETWORK = 368,
  CEER_66_CALL_ALREADY_CLEARED = 369,
  CEER_66_SEMANTICALLY_INCORRECT_MESSAGE2 = 370,
  CEER_66_INVALID_MANDATORY_INFO = 371,
  CEER_66_MESSAGE_TYPE_NON_EXISTING = 372,
  CEER_66_MESSAGE_TYPE_INCOMPATIBLE_IN_STATE = 373,
  CEER_66_CONDITIONAL_INFORMATION_ELEMENT_ERROR = 374,
  CEER_66_NO_CELL_ALLOCATION_AVAILABLE = 375,
  CEER_66_PROTOCOL_ERROR_UNSPECIFIED2 = 376,
  CEER_66_NORMAL_EVENT = 377,
  CEER_66_UNSPECIFIED = 378,
  CEER_66_PREEMPTIVE_RELEASE2 = 379,
  CEER_66_CONGESTION = 380,
  CEER_66_RE_ESTABLISHMENT_REJECT = 381,
  CEER_66_DIRECTED_SIG_CONN_ESTABLISHMENT = 382,
  CEER_66_USER_INACTIVITY = 383,
  CEER_66_LOWER_LAYER_FAILURE_DOWNLINK = 384,
  CEER_66_LOWER_LAYER_FAILURE_UPLINK = 385,
  CEER_66_CELL_BARRED_DUE_TO_AUTHENTICATION_FAILURE = 386,
  CEER_66_SIGNALLING_CONNECTION_RELEASE = 387,
  CEER_66_CS_CONNECTION_RELEASE_TRIGGERED_BY_MM = 388,
  CEER_66_RRC_CONNECTION_ESTABLISHMENT_FAILURE = 389,
  CEER_66_RRC_CONNECTION_ESTABLISHMENT_RE_JECT_WITH_REDIRECTION = 390,
  CEER_66_RESOURCE_CONFLICT = 391,
  CEER_66_LAYER_2_SEQUENCE_ERROR = 392,
  CEER_66_LAYER_2_T200_EXP_N200_PLUS_1_TIMES = 393,
  CEER_66_LAYER_2_UNSOLICITED_DM_RESP_MFES = 394,
  CEER_66_LAYER_2_CONTENTION_RESOLUTION = 395,
  CEER_66_LAYER_2_NORMAL_CAUSE = 396,
  CEER_66_RR_CONNECTION_RELEASE_DUE_TO_BAND_CHANGE_2G = 397,
  CEER_66_MM_RR_CONNECTION_ERROR_WHILE_RELEASE = 400,
  CEER_66_USER_DISCONNECTED = 500,
  CEER_66_REMOTE_USER_NW_DISCONNECTED_FOR_CALL_STATUS_RATHER_THAN_CALL_PROCEEDING = 510,
  CEER_66_REMOTE_USER_NW_DISCONNECTED_FOR_CALL_STATUS_IS_CALL_PROCEEDING = 511,
  CEER_66_REQUEST_REJECTED_BCM_VIOLATION = 512,
};

enum
{
  CEER_71_UNKNOWN_PROBLEM = 0,
  CEER_71_MEMORY_PROBLEM = 1,
  CEER_71_FILE_ID_NOT_FOUND = 2,
  CEER_71_INCREASE_PROBLEM = 6,
  CEER_71_TECHNICAL_PROBLEM = 7,
  CEER_71_COMMAND_NOT_ALLOWED = 11,
  CEER_71_SIM_CARD_OUT = 15,
};

enum
{
  MODEM_CALL_ACTIVE = 0,
  MODEM_CALL_HELD,
  MODEM_CALL_DIALING,
  MODEM_CALL_ALERTING,
  MODEM_CALL_INCOMING,
  MODEM_CALL_WAITING,

  modem_call_state_num,
};

enum
{
  NO_CALL_IN_PROGRESS = 0,
  CALL_IN_PROGRESS = 1,
};


#endif